api:
  build: ./feeder
  ports:
   - "3000:3000"
  volumes:
   - /Users/marklapierre/Dropbox/Dev/rss/reader_api/feeder:/code
  links:
   - pgdb
  env_file:
   - ./feeder/config/.env
pgdb:
  build: ./feeder_db
  volumes_from:
   - feeder_data
  ports:
   - "5432:5432"
  expose:
   - "5432"
  volumes:
   - /Users/marklapierre/Dropbox/Dev/rss/reader_api/feeder_db:/code
web:
  build: ./reader
  ports:
   - "8000:8000"   
  links:
   - api
  environment:
    API_ADDR: boot2docker
    API_PORT: 3000
    COUCHDB_ADDR: boot2docker
    COUCHDB_PORT: 5984
  volumes:
   - /Users/marklapierre/Dropbox/Dev/rss/reader_api/reader:/code
couchdb:
  build: ./couchdb
  ports:
   - "5984:5984"
  expose:
   - "5984"
  volumes:
   - /Users/marklapierre/Dropbox/Dev/rss/reader_api/couchdb:/code
readerapi:
  build: ./reader_api
  ports:
   - "3001:3001"
  volumes:
   - /Users/marklapierre/Dropbox/Dev/rss/reader_api/reader_api:/code
  links:
   - pgdb
  env_file:
   - ./reader_api/src/github.com/mlapierre/reader_api/.env
