api:
  build: ./feeder
  ports:
   - "3000:3000"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/feeder:/code
  links:
   - pgdb
  env_file:
   - ./feeder/config/.env
pgdb:
  build: ./feeder_db
  ports:
   - "5432:5432"
  expose:
   - "5432"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/feeder_db:/code
web:
  build: ./reader
  ports:
   - "8000:8000"
  links:
   - api
   - couchdb
  environment:
    API_ADDR: boot2docker
    API_PORT: 3000
    COUCHDB_ADDR: boot2docker
    COUCHDB_PORT: 5984
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/reader:/code
couchdb:
  build: ./couchdb
  ports:
   - "5984:5984"   
  expose:
   - "5984"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/couchdb:/code
