api:
  build: ./feeder
  ports:
   - "3000:3000"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/feeder:/code
  links:
   - pgdb
  env_file:
   - ./feeder/config/.env
pgdb:
  build: ./feeder_db
  ports:
   - "5432:5432"
  expose:
   - "5432"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/feeder_db:/code
web:
  build: ./reader
  ports:
   - "8000:8000"   
  links:
   - api
  environment:
    API_ADDR: boot2docker
    API_PORT: 3000
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/master/reader:/code
