api:
  build: ./feeder
  ports:
   - "3000:3000"
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/reader_prototype/feeder:/code
  env_file:
   - ./feeder/config/.env
web:
  build: ./reader
  ports:
   - "8000:8000"   
  links:
   - api
  environment:
    API_ADDR: boot2docker
    API_PORT: 3000
  volumes:
   - /mnt/mydocs/Dropbox/Dev/rss/reader_prototype/reader:/code
