source 'http://rubygems.org'

case RUBY_PLATFORM
  when /x64-mingw32/
    ruby '2.0.0'
  when /i386-mingw32/
    ruby '1.9.3'
  when /java/
    ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.12'
  else
    raise RuntimeError "Invalid OS #{RUBY_PLATFORM}"
end

group :development do
  gem 'pry'
end

group :test do
end

#gem 'feedjira'
gem 'simple-rss'
gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'mongoid', '~> 4.0.0.rc1', git: 'https://github.com/mongoid/mongoid.git'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '>= 4.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw_20]
