FROM klaemo/couchdb:latest

COPY local.ini /usr/local/etc/couchdb/

#RUN apt-get update -y \
#  && apt-get install -y --no-install-recommends curl apt-transport-https

#RUN curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
#  && echo 'deb https://deb.nodesource.com/node wheezy main' > /etc/apt/sources.list.d/nodesource.list \
#  && echo 'deb-src https://deb.nodesource.com/node wheezy main' >> /etc/apt/sources.list.d/nodesource.list \
#  && apt-get update -y && apt-get install -y nodejs

#RUN npm install -g add-cors-to-couchdb && add-cors-to-couchdb
